### ISSUE TITLE
Data comparison DataGridView errors with Timestamp/RowVersion columns

### ISSUE THREAD

**Issue by pricerc** [OpenDBDiff/OpenDBDiff#107]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of OpenDBDiff**

0.10.0.0

**What is the current behavior?**

Little white boxes with a red 'x' in them, and the following exception:

`
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.ImageConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Forms.Formatter.FormatObject(Object value, Type targetType, TypeConverter sourceConverter, TypeConverter targetConverter, String formatString, IFormatProvider formatInfo, Object formattedNullValue, Object dataSourceNullValue)
   at System.Windows.Forms.DataGridViewCell.GetFormattedValue(Object value, Int32 rowIndex, DataGridViewCellStyle& cellStyle, TypeConverter valueTypeConverter, TypeConverter formattedValueTypeConverter, DataGridViewDataErrorContexts context)
`

for each cell displayed. Which can be quite distracting if you have lots of them.

**What is the expected behavior or new feature?**

Instead of trying to display an image, the grid needs to replace the 'image' column with readonly 'text' column that displays something useful; maybe the timestamp in hex.

As an interim measure, handling DataError at least prevents the annoying popup, but there is still the unhelpful red 'x'.

**Did this work in previous versions of our tool?  If so, in which versions?**

Don't know.

## Reproducibility
Compare data on table with a timestamp/rowversion data type in the table.

**Comment by pricerc** [comment]
The minimal quick and dirty to make the diff functional is to add an error handler to DataCompareForm.cs:

```C#
...
            srcDgv.DataError += new DataGridViewDataErrorEventHandler(dgv_DataError);
            destDgv.DataError += new DataGridViewDataErrorEventHandler(dgv_DataError);
...

        private void dgv_DataError(object sender, DataGridViewDataErrorEventArgs e)
        {
            // handle errors a bit more elegantly than the default.
            System.Diagnostics.Debug.Print(e.Exception.ToString());
        }

```

But I also added this to just replace each `DataGridViewImageColumn` with `DataGridViewTextBoxColumn` that displays the byte array as a hex string:

``` C#
private void doCompare()
        {
...



            srcDgv.DataError += new DataGridViewDataErrorEventHandler(dgv_DataError);
            destDgv.DataError += new DataGridViewDataErrorEventHandler(dgv_DataError);

            if (FixTimestampColumns(srcDgv) > 0)
                srcDgv.CellFormatting +=
                        new DataGridViewCellFormattingEventHandler(binary_CellFormatting);

            if (FixTimestampColumns(destDgv) > 0)
                destDgv.CellFormatting +=
                        new DataGridViewCellFormattingEventHandler(binary_CellFormatting);

        }

        private int FixTimestampColumns(DataGridView grid)
        {
            var table = (DataTable)grid.DataSource;

            // get readonly byte[] columns; they're *probably* a timestamp.
            var victims = grid.Columns.OfType<DataGridViewImageColumn>()
                .Where(gc => table.Columns[gc.DataPropertyName].ReadOnly)
                .ToList();

            foreach (var victim in victims)
            {
                grid.Columns.Remove(victim);
                grid.Columns.Insert(victim.Index, new DataGridViewTextBoxColumn()
                {
                    ReadOnly = true
                    ,
                    DataPropertyName = victim.DataPropertyName
                    ,
                    Name = victim.Name
                });
            }
            return victims.Count;
        }

        private void dgv_DataError(object sender, DataGridViewDataErrorEventArgs e)
        {
            // handle errors a bit more elegantly than the default.
            System.Diagnostics.Debug.Print(e.Exception.ToString());
        }

        private void binary_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
        {
            var grid = (DataGridView)sender;
            if (!(grid.Columns[e.ColumnIndex] is DataGridViewTextBoxColumn)) return;
            if (grid.Columns[e.ColumnIndex].ValueType != typeof(byte[])) return;

            var table = (DataTable)grid.DataSource;
            if (e.RowIndex >= table.Rows.Count) return;

            e.Value = FormatByteArray((byte[])e.Value, 64);
            e.FormattingApplied = true;
            return;
        }

        private static object FormatByteArray(byte[] data, int maxLength)
        {
            var result = new StringBuilder(maxLength);
            for (int i = 0; i < maxLength && i < data.Length; i++)
            {
                result.Append(data[i].ToString("X2"));
            }
            return result.ToString();
        }

```


I would consider a PR, but that's not something I'm comfortable with at this stage (having not done one before!)

**Comment by pricerc** [comment]
Also in the same form; the Z-Order for the data grids is wrong, so the column headers are hidden by the Source/Destination headers.

**Comment by igitur** [comment]
> I would consider a PR, but that's not something I'm comfortable with at this stage (having not done one before!)

We were all there at one stage. Just have to jump in.
