### ISSUE TITLE
Unhanded Exception

### ISSUE THREAD

**Issue by axanth** [OpenDBDiff/OpenDBDiff#110]
Error information
Error Loading Server: SKULL\SQLEXPRESS, Database: odaNiceAndEasy (while Reading XML Schema...)
SqlException: This functionality requires .NET Framework 3.5 SP1. Please install .NET Framework 3.5 SP1 to use this functionality.
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.GenerateAssemblies.Fill(Database database, String connectionString) in OpenDBDiff.Schema.SQLServer.Generates\Generates\GenerateAssemblies.cs:line 72
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in OpenDBDiff.Schema.SQLServer.Generates\Generates\Generate.cs:line 125
   at OpenDBDiff.Schema.SQLServer.Generates.Front.SQLServerGenerator.Process() in OpenDBDiff.Schema.SQLServer2005\Front\SQLServerGenerator.cs:line 36
   at OpenDBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, EventArgs e) in OpenDBDiff\Front\ProgressForm.cs:line 65

4119EE2142F3869D0BA869B004FAB127

**Comment by igitur** [comment]
This functionality requires .NET Framework 3.5 SP1. Please install .NET Framework 3.5 SP1 to use this functionality.
