### ISSUE TITLE
Error in execution

### ISSUE THREAD

**Issue by rohitnair029** [OpenDBDiff/OpenDBDiff#112]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of OpenDBDiff**

e.g. 0.10.0.0

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  If so, in which versions?**

Yes/No/v0.XX

## Reproducibility
Please attach schema generation scripts for the relevant database objects. If your bug report is about changing existing entities (i.e. not creating or dropping an object), please attach the scheme generation scripts of the object before and after the change. This will enable the developers to reproduce your problem easily. Highlight particular areas of interest.

#### Before schema change:
```sql
CREATE TYPE [dbo].[MyTableType] AS TABLE(
	[Column1] [varchar](30) NOT NULL,
	[Column2] [date] NOT NULL,
	[Column3] [varchar](5) NOT NULL -- This column will be dropped
)
```

#### After schema change:
```sql
CREATE TYPE [dbo].[MyTableType] AS TABLE(
	[Column1] [varchar](30) NOT NULL,
	[NewColumn] [datetime] NOT NULL, -- This column was added
	[Column2] [date] NULL -- This column now allows NULL values
)
```
###ERROR DETAILS : 

1.  To report an error search first in the Github issues to see if it's already been reported.
2a. If there is no issue, click 'New issue' and paste the error details
    into the body of the issue. To copy the error press "Copy error"
    (At least email the details to opendbdiff@gmail.com)

2b. If the issue exists, but your situation is different please leave a comment with the details.

•   If possible, please attach a SQL script creating the two databases with
    the minimum necessary to reproduce the problem.

Error information
Error Loading Server: EDW-dc1.eyua.net,17001, Database: EDW_DATA_DEV1 (while initializing)
InvalidCastException: Specified cast is not valid.
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.GenerateDatabase.Get(Database database) in OpenDBDiff.Schema.SQLServer.Generates\Generates\GenerateDatabase.cs:line 89
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in OpenDBDiff.Schema.SQLServer.Generates\Generates\Generate.cs:line 83
   at OpenDBDiff.Schema.SQLServer.Generates.Front.SQLServerGenerator.Process() in OpenDBDiff.Schema.SQLServer2005\Front\SQLServerGenerator.cs:line 36
   at OpenDBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, EventArgs e) in OpenDBDiff\Front\ProgressForm.cs:line 65

D39E008BEAACC9E1ADB0B9BF1160FA6D

**Comment by igitur** [comment]
Please complete the *entire* [issue template](https://github.com/OpenDBDiff/OpenDBDiff/blob/develop/.github/ISSUE_TEMPLATE.md), including the schemas for reproducibility.
