### ISSUE TITLE
NotImplementedException: The Method or operation is not implemented

### ISSUE THREAD

**Issue by NeilMJohnson** [OpenDBDiff/OpenDBDiff#113]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

Version:
V0.10

**What is the current behavior?**

Create new project
Connect to two databases on the same server.
Do a compare.
Exception results.

**What is the expected behavior or new feature?**
Should work without an exception.

**Did this work in previous versions of our tool?  If so, in which versions?**

Yes - but on SQL Server 2005 - now using SQL Server Express 2008

Error information
Error Generating Synchronized Script
NotImplementedException: The method or operation is not implemented.
   at OpenDBDiff.Schema.Model.SchemaBase.Drop() in OpenDBDiff.Schema\Model\SchemaBase.cs:line 145
   at OpenDBDiff.Schema.SQLServer.Generates.Model.Code.RebuildDependencys(List`1 depends, Int32 deepMin, Int32 deepMax) in OpenDBDiff.Schema.SQLServer.Generates\Model\Code.cs:line 170
   at OpenDBDiff.Schema.SQLServer.Generates.Model.Function.ToSqlDiff(ICollection`1 schemas) in OpenDBDiff.Schema.SQLServer.Generates\Model\Function.cs:line 57
   at OpenDBDiff.Schema.Model.SchemaList`2.ToSqlDiff(ICollection`1 schemas) in OpenDBDiff.Schema\Model\SchemaList.cs:line 129
   at OpenDBDiff.Schema.SQLServer.Generates.Model.Database.ToSqlDiff(ICollection`1 schemas) in OpenDBDiff.Schema.SQLServer.Generates\Model\Database.cs:line 236
   at OpenDBDiff.Front.PrincipalForm.StartComparison() in OpenDBDiff\Front\PrincipalForm.cs:line 70

4287F00A7B17D74D5BD3EEF9F05F9B42

**Comment by NeilMJohnson** [comment]
Running this in Visual Studio - the line in the RebuildDependencyList where it is checking the ObjectType, it is set to Table.  The item.Parent is:
Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    ActionMessage: {OpenDBDiff.Schema.SqlAction}
    AllObjects: {OpenDBDiff.Schema.Model.SearchSchemaBase}
    Assemblies: Count = 0
    CLRFunctions: Count = 0
    CLRProcedures: Count = 0
    ChangesOptions: Count = 0
    DDLTriggers: Count = 0
    Defaults: Count = 0
    Dependencies: Count = 1112
    DependenciesCount: 0
    ExtendedProperties: Count = 0
    FileGroups: Count = 0
    FullName: "[MortgageProDemo]"
    FullText: Count = 0
    Functions: Count = 62
    Guid: "e1b79d11-8ca1-490b-88aa-23cfb3e2058d"
    HasDependencies: false
    Id: 0
    Info: {OpenDBDiff.Schema.SQLServer.Generates.Model.DatabaseInfo}
    IsCaseSensitive: false
    IsCodeType: false
    IsSystem: false
    MustBuildSqlInLine: false
    Name: "MortgageProDemo"
    ObjectType: Database
    OpenDBDiff.Schema.Model.IDatabase.Options: {OpenDBDiff.Schema.SQLServer.Generates.Options.SqlOption}
    Options: {OpenDBDiff.Schema.SQLServer.Generates.Options.SqlOption}
    Owner: null
    Parent: null
    PartitionFunctions: Count = 0
    PartitionSchemes: Count = 0
    Procedures: Count = 202
    Roles: Count = 18
    RootParent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    Rules: Count = 10
    Schemas: Count = 9
    SourceInfo: {OpenDBDiff.Schema.SQLServer.Generates.Model.DatabaseInfo}
    Status: Rebuild
    Synonyms: Count = 0
    Tables: Count = 125
    TablesTypes: Count = 0
    UserTypes: Count = 12
    Users: Count = 0
    Views: Count = 79
    XmlSchemas: Count = 0
    _changesOptions: Count = 0
    nameCharacterClose: "]"
    nameCharacterOpen: "["
    parent: null
    rootParent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    status: Rebuild
    wasInsertInDiffList: null

The item is:
Id: 1281751969 - Name: "MORTGAGES" - Status: Alter
    CLRTriggers: Count = 0
    Columns: Count = 131
    CompressType: null
    Constraints: Count = 11
    DependenciesCount: 1
    ExtendedProperties: Count = 1189
    FileGroup: null
    FileGroupStream: null
    FileGroupText: null
    FullName: "[dbo].[MORTGAGES]"
    FullTextIndex: Count = 0
    Guid: "47da0e99-b470-4a36-b2ae-f54c11c4c274"
    HasBlobColumn: true
    HasChangeDataCapture: false
    HasChangeTracking: false
    HasChangeTrackingTrackColumn: false
    HasClusteredIndex: false
    HasDependencies: true
    HasFileStream: false
    HasIdentityColumn: true
    Id: 1281751969
    Indexes: Count = 11
    IsCodeType: false
    IsSystem: false
    MustBuildSqlInLine: false
    Name: "MORTGAGES"
    ObjectType: Table
    Options: Count = 1
    OriginalTable: Id: 1281751969 - Name: "MORTGAGES" - Status: Original
    Owner: "dbo"
    Parent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    Partitions: Count = 0
    RootParent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    Status: Alter
    Triggers: Count = 11
    dependencies: null
    dependenciesCount: 1
    hasFileStream: false
    nameCharacterClose: "]"
    nameCharacterOpen: "["
    parent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    rootParent: Id: 0 - Name: "MortgageProDemo" - Status: Rebuild
    status: Alter
    wasInsertInDiffList: null

Even thought I have set the preferred method to Alter, as I understand it, it still seems to be trying to Drop./Add the table. When it calls at line 170 in Code.cs:
list.Add(item.Drop(), newDeepMin);
the Drop is not implemented for the Table type.

**Comment by NeilMJohnson** [comment]
I am running the version that is on this site as of June 14, 2019.

**Comment by NeilMJohnson** [comment]
I checked the .9 version which ran correctly against the SQL Server 2005 version of the database and it has the same problem with the SQL Server 2008 database.

**Comment by igitur** [comment]
Please complete the entire issue [issue template](https://github.com/OpenDBDiff/OpenDBDiff/blob/develop/.github/ISSUE_TEMPLATE.md), including the schemas for reproducibility.
