### ISSUE TITLE
String to DateTime conversion error when comparing databases

### ISSUE THREAD

**Issue by majgab8852** [OpenDBDiff/OpenDBDiff#137]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of OpenDBDiff**

0.13.0.191

**What is the current behavior?**

When running the tool on two versions of the database (one local, one copied from remote server), it produces the following error:

```
1.  To report an error search first in the Github issues to see if it's already been reported.
2a. If there is no issue, click 'New issue' and paste the error details
    into the body of the issue. To copy the error press "Copy error"
    (At least email the details to opendbdiff@gmail.com)

2b. If the issue exists, but your situation is different please leave a comment with the details.

•   If possible, please attach a SQL script creating the two databases with
    the minimum necessary to reproduce the problem.

Error information
Error Generating Synchronized Script
FormatException: String was not recognized as a valid DateTime.
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.<>c__DisplayClass35_0.<ToSql>b__1(String item) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 97
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSql() in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 97
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 189
   at OpenDBDiff.Abstractions.Schema.Model.SchemaList`2.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.Abstractions.Schema\Model\SchemaList.cs:line 129
   at OpenDBDiff.SqlServer.Schema.Model.Database.ToSqlDiff(ICollection`1 schemas) in C:\projects\opendbdiff\OpenDBDiff.SqlServer.Schema\Model\Database.cs:line 237
   at OpenDBDiff.UI.MainForm.StartComparison() in C:\projects\opendbdiff\OpenDBDiff\UI\MainForm.cs:line 71

07DA60DA4D5F603C6A86087436DEC991
```

**What is the expected behavior or new feature?**

Expactation is that I get a comparison of differences.

**Did this work in previous versions of our tool?  If so, in which versions?**

N/A. Not tested with other version.

## Reproducibility

Unfortunately I have no idea which of the 60+ tables is causing the issue... or which column in those tables, or which value. I can't even see what is the value of the string which OpenDBDiff cannot convert to date. I'm not at liberty to share the full database creation script, nor the full data, but if I can pinpoint what value is causing the error, I can try to reproduce it manually.

**Comment by majgab8852** [comment]
Just a note: when doing the same on two other databases (also one local one copied from same remote server), same issue does not happen.

**Comment by majgab8852** [comment]
Strangely enough, it works on the same two databases in reverse: DB2 as source and DB1 as destination is OK, DB1 as source and DB2 as destination (what I needed) creates above error.

Is there any chance to pinpoint this error further? Maybe some extra logging in the application?

**Comment by jspraul** [comment]
It looks like a partition function by date is having trouble parsing one of the dates.

You may be able to compare the rest of the database objects by opening 'Options' and un-checking 'Partition functions' on the 'Filter by type' tab.

**Comment by majgab8852** [comment]
First of all: when I disable the partition function and/or partition scheme, and I click 'Apply', when I open the 'Options' again, it's enabled again.

However, I think I managed to reproduce the issue. It's somewhat my fault :) Allow me to explain:

- We have a product, which stores (among others) reporting data in the database. Reporting data is stored in a few tables, which are all partitioned using a partition function and partition scheme.
- At the moment we are in the process of upgrading our product at one location, and to be able to 100% test our upgrade script, we:
  - Exported the production database
  - Imported into the test database server under a different name
  - Truncated all report tables (to save disk space as it barely fit, and also because it contained live production data)
  - Eventually dropped all report tables, dropped the partition function and partition scheme, dropped the data files belonging to the partitions, and recreated the report tables empty and non-partitioned
- Then I tried to compare, and got the above error
- Today I dropped the imported production database, imported the same again, and didn't do the modifications I listed above, and comparing started to work without any hassle.
- So I did the same thing I did on Friday (dropping objects as I listed above), and the issue occurred again.

So it seems issue is caused when you have the same object in two databases, source database is partitioned, but destination database is not.

I'll try to create a simpler example and provide the script for it.

**Comment by majgab8852** [comment]
I created the attached script, it's reproducing the issue for me when selecting 'Test1' database as source and 'Test2' as destination. I have to upload it as a TXT, GitHub won't accept it.

[OpenDBDiff_issue_137_script.txt](https://github.com/OpenDBDiff/OpenDBDiff/files/6919544/OpenDBDiff_issue_137_script.txt)

I also wanted to specify DB version:

```
SELECT @@VERSION;

Microsoft SQL Server 2017 (RTM-CU24) (KB5001228) - 14.0.3391.2 (X64)   Apr 28 2021 10:32:18   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```
