### ISSUE TITLE
String ''2020-01-01 00:00:00.000'' was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by FreeVB** [OpenDBDiff/OpenDBDiff#172]
FormatException: String ''2020-01-01 00:00:00.000'' was not recognized as a valid DateTime.
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.<>c__DisplayClass35_0.<ToSql>b__1(String item) in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 98   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSql() in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 98
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSqlAdd() in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 114
   at OpenDBDiff.SqlServer.Schema.Model.PartitionFunction.ToSqlDiff(ICollection`1 schemas) in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.SqlServer.Schema\Model\PartitionFunction.cs:line 193
   at OpenDBDiff.Abstractions.Schema.Model.SchemaList`2.ToSqlDiff(ICollection`1 schemas) in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.Abstractions.Schema\Model\SchemaList.cs:line 119
   at OpenDBDiff.SqlServer.Schema.Model.Database.ToSqlDiff(ICollection`1 schemas) in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff.SqlServer.Schema\Model\Database.cs:line 249
   at OpenDBDiff.UI.MainForm.StartComparison() in F:\MyDeskTop\OpenDBDiff-develop\OpenDBDiff\UI\MainForm.cs:line 56

What is the reason for this tip? How should I set the options or fix them?

**Comment by FreeVB** [comment]
I unfiltered the Partition functions, but I still chose it after turning on the options again.
