### ISSUE TITLE
An unexpected error has occured during processing.

### ISSUE THREAD

**Issue by mPremraj** [OpenDBDiff/OpenDBDiff#38]
An unexpected error has occured during processing.

    1. To report an error please, search first in the github issues to see if it's already solved.
    2a. If there is no issue, *Please* click 'Create New Issue' and paste the error details
        into the Description field. To copy the error press _Copy Error_
        (At least email the details to opendbdiff@gmail.com...)

    2b. If the issue exists, but your situation is different please leave a comment with the details.

    • If possible, please attach a SQL script creating two dbs with
        the minimum necessary to reproduce the problem.
    
Error Information
Error Loading Destination Database (while initializing)
SqlException: The operating system returned error 21(The device is not ready.) to SQL Server during a read at offset 0x00000023dae000 in file 'D:\d1_db\r2_db.mdf'. Additional messages in the SQL Server error log and system event log may provide more detail. This is a severe system-level error condition that threatens database integrity and must be corrected immediately. Complete a full database consistency check (DBCC CHECKDB). This error can be caused by many factors; for more information, see SQL Server Books Online.
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.GenerateRules.Fill(Database database, String connectionString) in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Generates\GenerateRules.cs:line 29
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Generates\Generate.cs:line 91
   at OpenDBDiff.Schema.SQLServer.Generates.Front.SQLServerGenerator.Process() in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer2005\Front\SQLServerGenerator.cs:line 36
   at OpenDBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, EventArgs e) in C:\projects\opendbdiff\OpenDBDiff\Front\ProgressForm.cs:line 63

BC696AA9B47DC542B83B8096882B8DF8

**Comment by ironicnet** [comment]
It seems that the SQL Server cannot load the database correctly. If it's a network drive, it maybe a connection problem. If it's a physical drive, you may have corrupted blocks or sectors.

**Comment by mPremraj** [comment]
FYI:
The database is valid and reachable  (local server). The database is up and running sql server. I believe, It comes from app. If possible, I'll investigate and update soon.
