### ISSUE TITLE
ArgumentException while Reading FullText Index

### ISSUE THREAD

**Issue by jspraul** [OpenDBDiff/OpenDBDiff#6]
The following exception was submitted to opendbdiff@gmail.com:

Open DBDiff Beta 0.9.0.0
Error Loading Destination Database (while Reading FullText index...)
ArgumentException: Format of the initialization string does not conform to specification starting at index 98.
 at DBDiff.Schema.SQLServer.Generates.Generates.Generate.get_Name() in ..\opendbiff\DBDiff.Schema.SQLServer2005\Generates\Generate.cs:line 42
 at DBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in ..\opendbiff\DBDiff.Schema.SQLServer2005\Generates\Generate.cs:line 90
 at DBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, Eventargs e) in ..\opendbdiff\DBDiff\Front\ProgressForm.cs:line 96

5534C60377D96428473764F1F6200547

![image-20170605](https://cloud.githubusercontent.com/assets/115931/26781277/abfa3e00-49bb-11e7-9358-086ec0a9ee9e.png)

**Comment by igitur** [comment]
Thanks. I think we'll have to relook at the way users submit those kinds of bugs. I don't have the time to look for bugs with the little information that exception generates. Ideally I'd like the full schemas of both sides, or at least the schemas of the entities that are being compared. You have any thoughts?

**Comment by jspraul** [comment]
Any such functionality should always include functionality similar to what is provided by the free SQL Sentry Plan Explorer tool's "Anonymize" button which implements the following:

![2017-06-05_07-15-50](https://cloud.githubusercontent.com/assets/115931/26781904/e0953c48-49be-11e7-9ded-3582606b0b07.png)

**Comment by ironicnet** [comment]
Taking into account that the error is ocurring in the getter of Name. I suppose that the connection string was invalid.
Maybe we should add a validation to the connection string before running the Process code
