### ISSUE TITLE
Object not set... error when generating differences

### ISSUE THREAD

**Issue by MarkGaze** [OpenDBDiff/OpenDBDiff#73]
When generating differences between databases, I get the following issue:

```
1.  To report an error search first in the Github issues to see if it's already been reported.
2a. If there is no issue, click 'New issue' and paste the error details
    into the body of the issue. To copy the error press "Copy error"
    (At least email the details to opendbdiff@gmail.com)

2b. If the issue exists, but your situation is different please leave a comment with the details.

•   If possible, please attach a SQL script creating the two databases with
    the minimum necessary to reproduce the problem.

Error information
Error Comparing Databases (while Reading Text Objects: [DocumentInsert])
NullReferenceException: Object reference not set to an instance of an object.
   at OpenDBDiff.Schema.Model.SchemaBase.set_Status(ObjectStatus value) in OpenDBDiff.Schema\Model\SchemaBase.cs:line 239
   at OpenDBDiff.Schema.Model.SchemaBase.set_Status(ObjectStatus value) in OpenDBDiff.Schema\Model\SchemaBase.cs:line 239
   at OpenDBDiff.Schema.Model.SchemaBase.set_Status(ObjectStatus value) in OpenDBDiff.Schema\Model\SchemaBase.cs:line 239
   at OpenDBDiff.Schema.SQLServer.Generates.Compare.CompareColumns.GenerateDifferences[T](Columns`1 originFields, Columns`1 destinationFields) in OpenDBDiff.Schema.SQLServer.Generates\Compare\CompareColumns.cs:line 81
   at OpenDBDiff.Schema.SQLServer.Generates.Compare.CompareTables.DoUpdate[Root](SchemaList`2 originFields, Table node) in OpenDBDiff.Schema.SQLServer.Generates\Compare\CompareTables.cs:line 14
   at OpenDBDiff.Schema.SQLServer.Generates.Compare.CompareBase`1.GenerateDifferences[Root](SchemaList`2 originFields, SchemaList`2 destinationFields) in OpenDBDiff.Schema.SQLServer.Generates\Compare\CompareBase.cs:line 54
   at OpenDBDiff.Schema.SQLServer.Generates.Compare.CompareDatabase.GenerateDifferences(Database origin, Database destination) in OpenDBDiff.Schema.SQLServer.Generates\Compare\CompareDatabase.cs:line 21

86EA0D2CEBDC074C8D1D3FED34E60F8D
```

It's strange because it is the `Parent` property that is null even though it is inside a `Parent != null` if statement... so that leads me to think it's a threading issue but haven't been able to prove it as yet.

**Comment by igitur** [comment]
Does `DocumentInsert` exist in both databases? Can you attach their create scripts? No data required.

**Comment by MarkGaze** [comment]
Just checking now ☺️

**Comment by MarkGaze** [comment]
We have more than one DocumentInsert proc in two different schema so just ran it to check which one it was and it's now failing (consistently) on a different proc...

[Old.txt](https://github.com/OpenDBDiff/OpenDBDiff/files/1860048/Old.txt)
[New.txt](https://github.com/OpenDBDiff/OpenDBDiff/files/1860049/New.txt)

**Comment by MarkGaze** [comment]
I added the scripts but have removed them as it seems to be nothing to do with them.

**Comment by MarkGaze** [comment]
I'm convinced that the DocumentInsert mention is a red herring, the error message is getting it from the last reported progress but I think it's moved on from stored procs to checking Tables by then (you can also see this in the stack trace above), I'll try and figure out which table it is to get the details of it.

**Comment by igitur** [comment]
OK, I'll look into it and probably update the error details for a more 'recent' description.

**Comment by MarkGaze** [comment]
Found it! It's this table:

[Old.txt](https://github.com/OpenDBDiff/OpenDBDiff/files/1860974/Old.txt)
[New.txt](https://github.com/OpenDBDiff/OpenDBDiff/files/1860975/New.txt)

Hopefully that helps
