### ISSUE TITLE
Crash when unchecking any checkbox in the Schema tab when no comparison has been run

### ISSUE THREAD

**Issue by MarkGaze** [OpenDBDiff/OpenDBDiff#83]
Found in v0.9.0.95

Repro Steps:

- Open OpenDBDiff
- Uncheck any of the checkboxes in the Schema tab
- OpenDBDiff will crash with the NullReferenceError below

`Stack Trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDBDiff.Front.SchemaTreeView.RebuildSchemaTree() in C:\projects\opendbdiff\OpenDBDiff\Front\SchemaTreeView.cs:line 156
   at OpenDBDiff.Front.SchemaTreeView.FilterCheckbox_CheckedChanged(Object sender, EventArgs e) in C:\projects\opendbdiff\OpenDBDiff\Front\SchemaTreeView.cs:line 260
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by MarkGaze** [comment]
The options should probably be disabled before a comparison has run or only take effect when the comparison completes.

When I found this issue, I was assuming that the options would take effect when the comparison was run.

**Comment by MarkGaze** [comment]
Will do, thanks @igitur

**Comment by MarkGaze** [comment]
Confirmed as fixed in 0.9.0.98 👍

**Comment by igitur** [comment]
Thanks. Also merged and released in v0.10.0 today. https://github.com/OpenDBDiff/OpenDBDiff/releases/tag/0.10.0
